Zapatos_web/Controllers/tallasController.cs
using entidades;
using logicanegocios.interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using logicanegocios.implementacion;

namespace Zapatos_web.Controllers
{
    public class tallasController : Controller
    {

        private ItallasLN objtallasLN = new TallasLN();
        // GET: tallas
        public ActionResult listartallas()
        {

            List<PA_Tallas_MostrarDetalle_Result> lobjRespuesta = new List<PA_Tallas_MostrarDetalle_Result>();

            try
            {
                lobjRespuesta = objtallasLN.mostrartallas();
            }
            catch (Exception ex)
            {
                throw ex;
            }


            return View(lobjRespuesta);
        }

        public ActionResult agregatallas()
        {
            return View();
        }

        public ActionResult modificatallas(int id)
        {

            PA_Tallas_MostrarDetallexid_Result lobjRespuesta = new PA_Tallas_MostrarDetallexid_Result();
            Tallas objtallas = new Tallas();

            try
            {
                lobjRespuesta = objtallasLN.mostrartallasxid(id);
                objtallas.IdTalla = id;
                objtallas.DscTalla = lobjRespuesta.DscTalla;


            }
            catch (Exception ex)
            {
                throw ex;
            }


            return View(objtallas);
        }

        public ActionResult eliminatallas(int id)
        {

            PA_Tallas_MostrarDetallexid_Result lobjRespuesta = new PA_Tallas_MostrarDetallexid_Result();
            Tallas objtallas = new Tallas();

            try
            {
                lobjRespuesta = objtallasLN.mostrartallasxid(id);
                objtallas.IdTalla = id;
                objtallas.DscTalla = lobjRespuesta.DscTalla;


            }
            catch (Exception ex)
            {
                throw ex;
            }


            return View(objtallas);
        }

        public ActionResult detalletallas(int id)
        {

            PA_Tallas_MostrarDetallexid_Result lobjRespuesta = new PA_Tallas_MostrarDetallexid_Result();
            Tallas objtallas = new Tallas();

            try
            {
                lobjRespuesta = objtallasLN.mostrartallasxid(id);
                objtallas.IdTalla = id;
                objtallas.DscTalla = lobjRespuesta.DscTalla;


            }
            catch (Exception ex)
            {
                throw ex;
            }


            return View(objtallas);
        }

        [HttpPost]
        public ActionResult acciones(string submitButton, Tallas ptallas)
        {

            try
            {
                switch (submitButton)
                {

                    case "Agregar":
                        return ingresartallas(ptallas);

                    case "Modificar":
                        return actualizartallas(ptallas);

                    case "Eliminar":
                        return eliminartallas(ptallas);
                    default:
                        return RedirectToAction("listartallas");

                }


            }
            catch (Exception ex)
            {
                throw ex;
            }

        }

        public ActionResult ingresartallas(Tallas ptallas)
        {
            List<PA_Tallas_MostrarDetalle_Result> lobjRespuesta = new List<PA_Tallas_MostrarDetalle_Result>();
            try
            {

                if (objtallasLN.insertartallas(ptallas))
                {
                    lobjRespuesta = objtallasLN.mostrartallas();
                }

            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View("listartallas", lobjRespuesta);
        }

        public ActionResult actualizartallas(Tallas ptallas)
        {
            List<PA_Tallas_MostrarDetalle_Result> lobjRespuesta = new List<PA_Tallas_MostrarDetalle_Result>();
            try
            {

                if (objtallasLN.actualizartallas(ptallas))
                {
                    lobjRespuesta = objtallasLN.mostrartallas();
                }

            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View("listartallas", lobjRespuesta);
        }

        public ActionResult eliminartallas(Tallas ptallas)
        {
            List<PA_Tallas_MostrarDetalle_Result> lobjRespuesta = new List<PA_Tallas_MostrarDetalle_Result>();
            try
            {

                if (objtallasLN.eliminartallas(ptallas))
                {
                    lobjRespuesta = objtallasLN.mostrartallas();
                }

            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View("listartallas", lobjRespuesta);
        }
    }
}

Zapatos_web/Views/tallas/agregatallas.cshtml
@model entidades.Tallas

@{
    ViewBag.Title = "agregatallas";
}

<h2>Agrega Tallas</h2>


@using (Html.BeginForm("acciones", "tallas", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        @*<hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdTalla, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdTalla, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdTalla, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.DscTalla, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DscTalla, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DscTalla, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" id="btnAgregar" name="submitButton"
                        value="Agregar" class="btn btn-primary" title="Agregar"
                        data-toggle="tooltip" data-container="body" data-placement="right">
                    Agregar
                </button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "listartallas")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Zapatos_web/Views/tallas/detalletallas.cshtml
@model entidades.Tallas

@{
    ViewBag.Title = "detalletallas";
}

<h2>Detalle Tallas</h2>

<div>
  
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdTalla)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdTalla)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DscTalla)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DscTalla)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Modificar", "modificatallas", new {id = Model.IdTalla }) |
    @Html.ActionLink("Regresar", "listartallas")
</p>

Zapatos_web/Views/tallas/eliminatallas.cshtml
@model entidades.Tallas

@{
    ViewBag.Title = "eliminatallas";
}

<h2>Elimina Tallas</h2>

<h3>Esta seguro(a) de que desea eliminarlo?</h3>
<div>
 
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdTalla)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdTalla)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DscTalla)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DscTalla)
        </dd>

    </dl>

    @using (Html.BeginForm("acciones", "tallas", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(model => model.IdTalla)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" id="btnEliminar" name="submitButton"
                        value="Eliminar" class="btn btn-primary" title="Eliminar"
                        data-toggle="tooltip" data-container="body" data-placement="right">
                    Eliminar
                </button>
                @Html.ActionLink("Regresar", "listartallas")
            </div>
        </div>


    }
</div>

Zapatos_web/Views/tallas/listartallas.cshtml
@model IEnumerable<entidades.PA_Tallas_MostrarDetalle_Result>

@{
    ViewBag.Title = "listartallas";
}

<h2>Lista Tallas</h2>

<p>
    @Html.ActionLink("Nuevo", "agregatallas")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdTalla)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DscTalla)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdTalla)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DscTalla)
        </td>
        <td>
            @Html.ActionLink("Modificar", "Modificar", new { id=item.IdTalla }) |
            @Html.ActionLink("Detalles", "Detalles", new { id = item.IdTalla }) |
            @Html.ActionLink("Eliminar", "Eliminar", new { id = item.IdTalla })
        </td>
    </tr>
}

</table>

Zapatos_web/Views/tallas/modificatallas.cshtml
@model entidades.Tallas

@{
    ViewBag.Title = "modificatallas";
}

<h2>Modificar Tallas</h2>


@using (Html.BeginForm("acciones", "tallas", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    @Html.ValidationMessageFor(model => model.DscTalla, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IdTalla)

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" id="btnmodificar" name="submitButton"
                    value="Modificar" class="btn btn-primary" title="Actualizar"
                    data-toggle="tooltip" data-container="body" data-placement="right">
                Actualizar
            </button>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Regresar", "listartallas")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}