Zapatos_web/Controllers/clientesController.cs
using entidades;
using logicanegocios.implementacion;
using logicanegocios.interfaces;
using System;
using System.Collections.Generic;
using System.Web.Mvc;


namespace Zapatos_web.Controllers
{

    public class clientesController : Controller
    {
        private IClientesLN objclientesLN = new ClientesLN();

        public ActionResult listarclientes()
        {

            List<PA_Clientes_MostrarDetalle_Result> lobjRespuesta = new List<PA_Clientes_MostrarDetalle_Result>();
            try
            {
                lobjRespuesta = objclientesLN.mostrarclientes();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View(lobjRespuesta);
        }

        public ActionResult agregaclientes()
        {

            return View();
        }

        public ActionResult actualizaclientes(int id)
        {
            PA_Clientes_MostrarDetallexid_Result lobjRespuesta = new PA_Clientes_MostrarDetallexid_Result();
            Clientes objclientes = new Clientes();
            try
            {
                lobjRespuesta = objclientesLN.mostrarclientesxid(id);
                objclientes.IdCliente =id;
                objclientes.Nombre = lobjRespuesta.Nombre;
                objclientes.Ap1 = lobjRespuesta.Ap1;
                objclientes.Ap2 = lobjRespuesta.Ap2;
                objclientes.telefono = lobjRespuesta.telefono;
                objclientes.email = lobjRespuesta.email;

            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View(objclientes);
        }

        public ActionResult eliminaclientes(int id)
        {
            PA_Clientes_MostrarDetallexid_Result lobjRespuesta = new PA_Clientes_MostrarDetallexid_Result();
            Clientes objclientes = new Clientes();
            try
            {
                lobjRespuesta = objclientesLN.mostrarclientesxid(id);
                objclientes.IdCliente = id;
                objclientes.Nombre = lobjRespuesta.Nombre;
                objclientes.Ap1 = lobjRespuesta.Ap1;
                objclientes.Ap2 = lobjRespuesta.Ap2;
                objclientes.telefono = lobjRespuesta.telefono;
                objclientes.email = lobjRespuesta.email;

            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View(objclientes);
        }

        public ActionResult detalleclientes(int id)
        {
            PA_Clientes_MostrarDetallexid_Result lobjRespuesta = new PA_Clientes_MostrarDetallexid_Result();
            Clientes objclientes = new Clientes();
            try
            {
                lobjRespuesta = objclientesLN.mostrarclientesxid(id);
                objclientes.IdCliente = id;
                objclientes.Nombre = lobjRespuesta.Nombre;
                objclientes.Ap1 = lobjRespuesta.Ap1;
                objclientes.Ap2 = lobjRespuesta.Ap2;
                objclientes.telefono = lobjRespuesta.telefono;
                objclientes.email = lobjRespuesta.email;

            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View(objclientes);
        }


        [HttpPost]
        public ActionResult acciones(string submitbutton, Clientes pclientes)
        {
            try
            {
                switch (submitbutton)
                {
                    case "Agregar":
                        return ingresaclientes(pclientes);

                    case "Modificar":
                        return actualizarclientes(pclientes);

                    case "Eliminar":
                        return eliminarclientes(pclientes);

                    default:
                        return RedirectToAction("listarclientes");
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
              
        }

        public ActionResult ingresaclientes(Clientes pclientes)
        {
            List<PA_Clientes_MostrarDetalle_Result> lobjRespuesta = new List<PA_Clientes_MostrarDetalle_Result>();
            try
            {
               if(objclientesLN.insertarcliente(pclientes))
                {
                    lobjRespuesta = objclientesLN.mostrarclientes();
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View("listarclientes", lobjRespuesta);
        }

        public ActionResult actualizarclientes(Clientes pclientes)
        {
            List<PA_Clientes_MostrarDetalle_Result> lobjRespuesta = new List<PA_Clientes_MostrarDetalle_Result>();
            try
            {
                if (objclientesLN.actualizarcliente(pclientes))
                {
                    lobjRespuesta = objclientesLN.mostrarclientes();
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View("listarclientes", lobjRespuesta);
        }

        public ActionResult eliminarclientes(Clientes pclientes)
        {
            List<PA_Clientes_MostrarDetalle_Result> lobjRespuesta = new List<PA_Clientes_MostrarDetalle_Result>();
            try
            {
                if (objclientesLN.eliminarcliente(pclientes))
                {
                    lobjRespuesta = objclientesLN.mostrarclientes();
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View("listarclientes", lobjRespuesta);
        }
    }
}

Zapatos_web/Views/clientes/actualizaclientes.cshtml
@model entidades.Clientes

@{
    ViewBag.Title = "actualizaclientes";
}

<h2>Actualizar Clientes</h2>


@using (Html.BeginForm("acciones", "clientes", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
   
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IdCliente)

    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ap1, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ap1, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ap1, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ap2, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ap2, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ap2, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.telefono, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" id="btnActualizar" name="submitbutton"
                    value="Modificar" class="btn btn-primary" title="Actualizar"
                    data-toggle="tooltip" data-container="body" data-placement="right">
                Actualizar
            </button>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Regresar", "listarclientes")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Zapatos_web/Views/clientes/agregaclientes.cshtml
@model entidades.Clientes

@{
    ViewBag.Title = "agregarclientes";
}

<h2>Agrega Clientes</h2>


@using (Html.BeginForm("acciones", "clientes", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
      
        <hr />
        @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdCliente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdCliente, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdCliente, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ap1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ap1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ap1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ap2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ap2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ap2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" id="btnAgregar" name="submitbutton"
                        value="Agregar" class="btn btn-primary" title="Agregar"
                        data-toggle="tooltip" data-container="body" data-placement="right">
                    Agregar
                </button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "listarclientes")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Zapatos_web/Views/clientes/detalleclientes.cshtml
@model entidades.Clientes

@{
    ViewBag.Title = "detalleclientes";
}

<h2>Detalles del Cliente</h2>

<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdCliente)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdCliente)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ap1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ap1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ap2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ap2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Modificar", "actualizaclientes", new { id = Model.IdCliente }) |
    @Html.ActionLink("Regresar", "listarclientes")
</p>

Zapatos_web/Views/clientes/eliminaclientes.cshtml
@model entidades.Clientes

@{
    ViewBag.Title = "eliminaclientes";
}

<h2>Eliminar Elientes</h2>

<h3>Esta seguro(a) de que desea eliminarlo?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ap1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ap1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ap2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ap2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

    </dl>

    @using (Html.BeginForm("acciones", "clientes", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(model => model.IdCliente)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" id="btnEliminar" name="submitbutton"
                        value="Eliminar" class="btn btn-primary" title="Eliminar"
                        data-toggle="tooltip" data-container="body" data-placement="right">
                    Eliminar
                </button>
                @Html.ActionLink("Regresar", "listarclientes")
            </div>
        </div>

        
    }
</div>

Zapatos_web/Views/clientes/listarclientes.cshtml
@model IEnumerable<entidades.PA_Clientes_MostrarDetalle_Result>

@{
    ViewBag.Title = "Clientes";
}

<h2>Lista Clientes</h2>

<p>
    @Html.ActionLink("Nuevo Cliente", "agregaclientes")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdCliente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ap1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ap2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.telefono)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdCliente)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ap1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ap2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.telefono)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.ActionLink("Modificar", "actualizaclientes", new { id=item.IdCliente }) |
            @Html.ActionLink("Detalle", "detalleclientes", new { id = item.IdCliente }) |
            @Html.ActionLink("Eliminar", "eliminaclientes", new { id = item.IdCliente })
        </td>
    </tr>
}

</table>