Zapatos_web/Controllers/tipozapatoController.cs
using logicanegocios.implementacion;
using logicanegocios.interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using entidades;

namespace Zapatos_web.Controllers
{
    public class tipozapatoController : Controller
    {

        private ItipozapatoLN objtipozapatoLN = new tipozapatoLN();
        // GET: tipozapato
        public ActionResult listartipozapato()
        {
            List<PA_TipoZapato_MostrarDetalle_Result> lobjRespuesta = new List<PA_TipoZapato_MostrarDetalle_Result>();

            try
            {
                lobjRespuesta= objtipozapatoLN.mostrartipozapato();
            }
            catch(Exception ex)
            {
                throw ex;
            }


            return View(lobjRespuesta);
        }

        public ActionResult agregatipozapato()
        {
            return View();
        }

        public ActionResult modificatipozapato(int id)
        {

          PA_TipoZapato_MostrarDetallexid_Result lobjRespuesta = new PA_TipoZapato_MostrarDetallexid_Result();
            TipoZapato objtipozapato = new TipoZapato();

            try
            {
                lobjRespuesta = objtipozapatoLN.mostrartipozapaotoxid(id);
                objtipozapato.IdTipoZapato = id;
                objtipozapato.DscTipoZapato = lobjRespuesta.DscTipoZapato;


            }
            catch (Exception ex)
            {
                throw ex;
            }


            return View(objtipozapato);
        }

        public ActionResult eliminatipozapato(int id)
        {

            PA_TipoZapato_MostrarDetallexid_Result lobjRespuesta = new PA_TipoZapato_MostrarDetallexid_Result();
            TipoZapato objtipozapato = new TipoZapato();

            try
            {
                lobjRespuesta = objtipozapatoLN.mostrartipozapaotoxid(id);
                objtipozapato.IdTipoZapato = id;
                objtipozapato.DscTipoZapato = lobjRespuesta.DscTipoZapato;


            }
            catch (Exception ex)
            {
                throw ex;
            }


            return View(objtipozapato);
        }

        public ActionResult detalletipozapato(int id)
        {

            PA_TipoZapato_MostrarDetallexid_Result lobjRespuesta = new PA_TipoZapato_MostrarDetallexid_Result();
            TipoZapato objtipozapato = new TipoZapato();

            try
            {
                lobjRespuesta = objtipozapatoLN.mostrartipozapaotoxid(id);
                objtipozapato.IdTipoZapato = id;
                objtipozapato.DscTipoZapato = lobjRespuesta.DscTipoZapato;


            }
            catch (Exception ex)
            {
                throw ex;
            }


            return View(objtipozapato);
        }


        [HttpPost]
        public ActionResult acciones(string submitButton, TipoZapato ptipozapato)
        {

            try
            {
              switch(submitButton)
                {

                    case "Agregar":
                        return ingresartipozapato(ptipozapato);

                    case "Modificar":
                        return actualizartipozapato(ptipozapato);

                    case "Eliminar":
                        return  eliminartipozapato(ptipozapato);
                    default:
                        return RedirectToAction("listartipozapato");

                }


            }
            catch (Exception ex)
            {
                throw ex;
            }

        }

        public ActionResult ingresartipozapato(TipoZapato ptipozapato)
        {
            List<PA_TipoZapato_MostrarDetalle_Result> lobjRespuesta = new List<PA_TipoZapato_MostrarDetalle_Result>();
            try
            {

              if(  objtipozapatoLN.insertartipozapato(ptipozapato))
                {
                    lobjRespuesta = objtipozapatoLN.mostrartipozapato();
                }

            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View("listartipozapato", lobjRespuesta);
        }

        public ActionResult actualizartipozapato(TipoZapato ptipozapato)
        {
            List<PA_TipoZapato_MostrarDetalle_Result> lobjRespuesta = new List<PA_TipoZapato_MostrarDetalle_Result>();
            try
            {

                if (objtipozapatoLN.actualizartipozapato(ptipozapato))
                {
                    lobjRespuesta = objtipozapatoLN.mostrartipozapato();
                }

            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View("listartipozapato", lobjRespuesta);
        }

        public ActionResult eliminartipozapato(TipoZapato ptipozapato)
        {
            List<PA_TipoZapato_MostrarDetalle_Result> lobjRespuesta = new List<PA_TipoZapato_MostrarDetalle_Result>();
            try
            {

                if (objtipozapatoLN.eliminartipozapato(ptipozapato))
                {
                    lobjRespuesta = objtipozapatoLN.mostrartipozapato();
                }

            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View("listartipozapato", lobjRespuesta);
        }
    }
}

Zapatos_web/Views/tipozapato/agregatipozapato.cshtml
@model entidades.TipoZapato

@{
    ViewBag.Title = "agregatipozapato";
}

<h2>Agrega Tipo Zapato</h2>


@using (Html.BeginForm("acciones", "tipozapato", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.IdTipoZapato, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdTipoZapato, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdTipoZapato, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.DscTipoZapato, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DscTipoZapato, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DscTipoZapato, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" id="btnAgregar" name="submitButton"
                        value="Agregar" class="btn btn-primary" title="Agregar"
                        data-toggle="tooltip" data-container="body" data-placement="right">
                    Agregar
                </button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "listartipozapato")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Zapatos_web/Views/tipozapato/detalletipozapato.cshtml
@model entidades.TipoZapato

@{
    ViewBag.Title = "detalletipozapato";
}

<h2>Detalle Tipo Zapato</h2>

<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdTipoZapato)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdTipoZapato)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DscTipoZapato)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DscTipoZapato)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Modificar", "modificatipozapato", new { id = Model.IdTipoZapato }) |
    @Html.ActionLink("Regresar", "listartipozapato")
</p>

Zapatos_web/Views/tipozapato/eliminatipozapato.cshtml
@model entidades.TipoZapato

@{
    ViewBag.Title = "eliminatipozapato";
}

<h2>Eliminar Tipo Zapato</h2>

<h3>Esta seguro(a) de que desea eliminarlo?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdTipoZapato)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdTipoZapato)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DscTipoZapato)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DscTipoZapato)
        </dd>

    </dl>

    @using (Html.BeginForm("acciones", "tipozapato", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(model => model.IdTipoZapato)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" id="btnEliminar" name="submitButton"
                        value="Eliminar" class="btn btn-primary" title="Eliminar"
                        data-toggle="tooltip" data-container="body" data-placement="right">
                    Eliminar
                </button>
                @Html.ActionLink("Regresar", "listartipozapato")
            </div>
        </div>

        
    }
</div>

Zapatos_web/Views/tipozapato/listartipozapato.cshtml
@model IEnumerable<entidades.PA_TipoZapato_MostrarDetalle_Result>

@{
    ViewBag.Title = "listartipozapato";
}

<h2>Lista Tipo Zapato</h2>

<p>
    @Html.ActionLink("Nuevo", "agregatipozapato")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdTipoZapato)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DscTipoZapato)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdTipoZapato)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DscTipoZapato)
        </td>
        <td>
            @Html.ActionLink("Modificar", "modificatipozapato", new { id=item.IdTipoZapato }) |
            @Html.ActionLink("Detalles", "detalletipozapato", new { id = item.IdTipoZapato }) |
            @Html.ActionLink("Eliminar", "eliminatipozapato", new { id = item.IdTipoZapato })
        </td>
    </tr>
}

</table>

Zapatos_web/Views/tipozapato/modificatipozapato.cshtml
@model entidades.TipoZapato

@{
    ViewBag.Title = "modificatipozapato";
}

<h2>Modifica Tipo Zapato</h2>


@using (Html.BeginForm("acciones", "tipozapato", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IdTipoZapato)

    <div class="form-group">
        @Html.LabelFor(model => model.DscTipoZapato, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DscTipoZapato, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DscTipoZapato, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" id="btnmodificar" name="submitButton"
                    value="Modificar" class="btn btn-primary" title="Actualizar"
                    data-toggle="tooltip" data-container="body" data-placement="right">
                Actualizar
            </button>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Regresar", "listartipozapato")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}