Zapatos_web/Controllers/pedidodetalleController.cs
using entidades;
using logicanegocios.implementacion;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Zapatos_web.Controllers
{
    public class pedidodetalleController : Controller
    {

        private pedidodetalleLN objpedidodetalleLN = new pedidodetalleLN();
        // GET: pedidodetalle
        public ActionResult listarpedidodetalle()
        {
            List<PA_Pedidodetalle_MostrarDetalle_Result> lobjRespuesta = new List<PA_Pedidodetalle_MostrarDetalle_Result>();
            try
            {
                lobjRespuesta = objpedidodetalleLN.mostrarpedidodetalle();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View(lobjRespuesta);
        }

        public ActionResult agregapedidodetalle()
        {

            return View();
        }

        public ActionResult actualizapedidodetalle(int id)
        {
            PA_Pedidodetalle_MostrarDetallexid_Result lobjRespuesta = new PA_Pedidodetalle_MostrarDetallexid_Result();
            PedidoDet objpedidodetalle = new PedidoDet();
            try
            {
                lobjRespuesta = objpedidodetalleLN.mostrarpedidodetallexid(id);
                objpedidodetalle.IdPedido = id;
                objpedidodetalle.IdZapato = lobjRespuesta.IdZapato;
                objpedidodetalle.Cantidad = lobjRespuesta.Cantidad;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View(objpedidodetalle);
        }

        public ActionResult eliminapedidodetalle(int id)
        {
            PA_Pedidodetalle_MostrarDetallexid_Result lobjRespuesta = new PA_Pedidodetalle_MostrarDetallexid_Result();
            PedidoDet objpedidodetalle = new PedidoDet();
            try
            {
                lobjRespuesta = objpedidodetalleLN.mostrarpedidodetallexid(id);
                objpedidodetalle.IdPedido = id;
                objpedidodetalle.IdZapato = lobjRespuesta.IdZapato;
                objpedidodetalle.Cantidad = lobjRespuesta.Cantidad;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View(objpedidodetalle);
        }

        public ActionResult detallepedidodetalle(int id)
        {
            PA_Pedidodetalle_MostrarDetallexid_Result lobjRespuesta = new PA_Pedidodetalle_MostrarDetallexid_Result();
            PedidoDet objpedidodetalle = new PedidoDet();
            try
            {
                lobjRespuesta = objpedidodetalleLN.mostrarpedidodetallexid(id);
                objpedidodetalle.IdPedido = id;
                objpedidodetalle.IdZapato = lobjRespuesta.IdZapato;
                objpedidodetalle.Cantidad = lobjRespuesta.Cantidad;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View(objpedidodetalle);
        }

        [HttpPost]
        public ActionResult acciones(string submitbutton, PedidoDet ppedidodetalle)
        {
            try
            {
                switch (submitbutton)
                {
                    case "Agregar":
                        return ingresapedidodetalle(ppedidodetalle);

                    case "Modificar":
                        return actualizarpedidodetalle(ppedidodetalle);

                    case "Eliminar":
                        return eliminarpedidodetalle(ppedidodetalle);

                    default:
                        return RedirectToAction("listarpedidodetalle");
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }

        }

        public ActionResult ingresapedidodetalle(PedidoDet ppedidodetalle)
        {
            List<PA_Pedidodetalle_MostrarDetalle_Result> lobjRespuesta = new List<PA_Pedidodetalle_MostrarDetalle_Result>();
            try
            {
                if (objpedidodetalleLN.insertarpedidodetalle(ppedidodetalle))
                {
                    lobjRespuesta = objpedidodetalleLN.mostrarpedidodetalle();
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View("listarpedidodetalle", lobjRespuesta);
        }


        public ActionResult actualizarpedidodetalle(PedidoDet ppedidodetalle)
        {
            List<PA_Pedidodetalle_MostrarDetalle_Result> lobjRespuesta = new List<PA_Pedidodetalle_MostrarDetalle_Result>();
            try
            {
                if (objpedidodetalleLN.actualizarpedidodetalle(ppedidodetalle))
                {
                    lobjRespuesta = objpedidodetalleLN.mostrarpedidodetalle();
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View("listarpedidodetalle", lobjRespuesta);
        }

        public ActionResult eliminarpedidodetalle(PedidoDet ppedidodetalle)
        {
            List<PA_Pedidodetalle_MostrarDetalle_Result> lobjRespuesta = new List<PA_Pedidodetalle_MostrarDetalle_Result>();
            try
            {
                if (objpedidodetalleLN.eliminarpedidodetalle(ppedidodetalle))
                {
                    lobjRespuesta = objpedidodetalleLN.mostrarpedidodetalle();
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View("listarpedidodetalle", lobjRespuesta);
        }

    }
}

Zapatos_web/Views/pedidodetalle/actualizapedidodetalle.cshtml
@model entidades.PedidoDet

@{
    ViewBag.Title = "actualizapedidodetalle";
}

<h2>Actualiza Pedido Detalle</h2>


@using (Html.BeginForm("acciones", "pedidodetalle", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IdPedido)


    <div class="form-group">
        @Html.LabelFor(model => model.IdZapato, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IdZapato, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IdZapato, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" id="btnActualizar" name="submitbutton"
                    value="Modificar" class="btn btn-primary" title="Actualizar"
                    data-toggle="tooltip" data-container="body" data-placement="right">
                Actualizar
            </button>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Regresar", "listarpedidodetalle")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Zapatos_web/Views/pedidodetalle/agregapedidodetalle.cshtml
@model entidades.PedidoDet

@{
    ViewBag.Title = "agregapedidodetalle";
}

<h2>Agrega Pedido Detalle</h2>


@using (Html.BeginForm("acciones", "pedidodetalle", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdPedido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdPedido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdPedido, "", new { @class = "text-danger" })
            </div>
        </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IdZapato, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IdZapato, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IdZapato, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" id="btnAgregar" name="submitbutton"
                    value="Agregar" class="btn btn-primary" title="Agregar"
                    data-toggle="tooltip" data-container="body" data-placement="right">
                Agregar
            </button>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Regresar", "listarpedidodetalle")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Zapatos_web/Views/pedidodetalle/detallepedidodetalle.cshtml
@model entidades.PedidoDet

@{
    ViewBag.Title = "detallepedidodetalle";
}

<h2>Detalle Pedido</h2>

<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdPedido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdPedido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdZapato)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdZapato)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cantidad)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Modificar", "actualizapedidodetalle", new { id = Model.IdPedido }) |
    @Html.ActionLink("Regresar", "listarpedidodetalle")
</p>

Zapatos_web/Views/pedidodetalle/eliminapedidodetalle.cshtml
@model entidades.PedidoDet

@{
    ViewBag.Title = "eliminapedidodetalle";
}

<h2>Elimina Pedido Detalle</h2>

<h3>Esta seguro(a) de que desea eliminarlo?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdPedido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdPedido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdZapato)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdZapato)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cantidad)
        </dd>

    </dl>

    @using (Html.BeginForm("acciones", "pedidodetalle", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(model => model.IdPedido)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" id="btnEliminar" name="submitbutton"
                        value="Eliminar" class="btn btn-primary" title="Eliminar"
                        data-toggle="tooltip" data-container="body" data-placement="right">
                    Eliminar
                </button>
                @Html.ActionLink("Regresar", "listarpedidodetalle")
            </div>
        </div>


    }
</div>

Zapatos_web/Views/pedidodetalle/listarpedidodetalle.cshtml
@model IEnumerable<entidades.PA_Pedidodetalle_MostrarDetalle_Result>

@{
    ViewBag.Title = "listarpedidodetalle";
}

<h2>Lista Pedido Detalle</h2>

<p>
    @Html.ActionLink("Nuevo ", "agregapedidodetalle")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdPedido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdCliente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cliente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FecPedido)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdPedido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdCliente)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cliente)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FecPedido)
        </td>
        <td>
            @Html.ActionLink("Modificar", "actualizapedidodetalle", new { id = item.IdPedido }) |
            @Html.ActionLink("Detalle", "detallepedidodetalle", new { id = item.IdPedido }) |
            @Html.ActionLink("Eliminar", "eliminapedidodetalle", new { id = item.IdPedido })
        </td>
    </tr>
}

</table>